<?php
$data = array (
  0 => 
  array (
    'cat_id' => '47',
    'cat_name' => '鞋/箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '58',
    'cat_name' => '首页',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '57',
    'cat_name' => '特色市场',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '54',
    'cat_name' => '家纺/居家',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '51',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '48',
    'cat_name' => '珠宝饰品/手表眼镜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '1',
    'cat_name' => '服装/内衣/配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '55',
    'cat_name' => '母婴玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '52',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '49',
    'cat_name' => '化妆品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '56',
    'cat_name' => '食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '53',
    'cat_name' => '家具建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '50',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '46',
    'cat_name' => '服饰配件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '2',
    'cat_name' => '品牌女装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 12,
  ),
  15 => 
  array (
    'cat_id' => '5',
    'cat_name' => '裤子',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '3',
  ),
  16 => 
  array (
    'cat_id' => '6',
    'cat_name' => '特色市场',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '3',
    'cat_name' => '裙装',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '3',
  ),
  18 => 
  array (
    'cat_id' => '7',
    'cat_name' => '其他分类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  19 => 
  array (
    'cat_id' => '4',
    'cat_name' => '上衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '17',
    'goods_num' => '8',
  ),
  20 => 
  array (
    'cat_id' => '15',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '16',
    'cat_name' => '半身裙',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '31',
    'cat_name' => '雪纺衫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '28',
    'cat_name' => '短外套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'PU外套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '19',
    'cat_name' => '毛呢外套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '32',
    'cat_name' => '马甲',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '29',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '26',
    'cat_name' => '风衣',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '23',
    'cat_name' => '皮草',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '20',
    'cat_name' => '毛衣',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '17',
    'cat_name' => '羽绒服',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '吊带/背心',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '30',
    'cat_name' => '卫衣/绒衫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '27',
    'cat_name' => '小西装',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '24',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '21',
    'cat_name' => '真皮皮衣',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '18',
    'cat_name' => '棉衣棉服',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '35',
    'cat_name' => '休闲裤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '36',
    'cat_name' => '正装裤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '37',
    'cat_name' => '打底裤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '34',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '41',
    'cat_name' => '唐装/中式服装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '38',
    'cat_name' => '中老年服装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '42',
    'cat_name' => '制服/校服',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '39',
    'cat_name' => '婚纱/礼服/旗袍',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '43',
    'cat_name' => '大码女装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '40',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '44',
    'cat_name' => '孕妇装',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '45',
    'cat_name' => '防辐射装',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '68',
    'cat_name' => '服饰内衣',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '94',
    'cat_name' => '食品保健',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '75',
    'cat_name' => '鞋包运动',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '59',
    'cat_name' => '美容珠宝',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '105',
    'cat_name' => '家灯装饰',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '86',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '99',
    'cat_name' => '家电数码',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '64',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '61',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'bb霜',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '62',
    'cat_name' => '洗护',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '66',
    'cat_name' => '黄金',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '男士',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '60',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '67',
    'cat_name' => '毛衣链',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '74',
    'cat_name' => '皮衣',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '71',
    'cat_name' => '毛衣',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '72',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '呢大衣',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '73',
    'cat_name' => '男羽绒',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '70',
    'cat_name' => '羽绒',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '80',
    'cat_name' => '跑步',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '77',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '90',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '84',
    'cat_name' => '男包',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '81',
    'cat_name' => '骑行',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '78',
    'cat_name' => '靴子',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '85',
    'cat_name' => '旅行箱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '82',
    'cat_name' => '瑜珈',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '79',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '76',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '83',
    'cat_name' => '女包',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '93',
    'cat_name' => '妈咪宝贝',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '87',
    'cat_name' => '宝宝食品',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '91',
    'cat_name' => '孕产',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '88',
    'cat_name' => '宝宝用品',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '92',
    'cat_name' => '宝宝爱学习',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '89',
    'cat_name' => '童装童鞋',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '96',
    'cat_name' => '零食坚果',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '97',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '98',
    'cat_name' => '提高免疫',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '95',
    'cat_name' => '进口零食',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '103',
    'cat_name' => '平板电脑',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '100',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '104',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '101',
    'cat_name' => '数码相机',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '102',
    'cat_name' => '笔记本',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '112',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '109',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '106',
    'cat_name' => '门',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '110',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '107',
    'cat_name' => '吊灯',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '111',
    'cat_name' => '柜类',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '108',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>